server:
  port: 8081
spring:
  application:
    name: cache-data-service
  datasource:
    url: jdbc:mysql://localhost:3306/CDS
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        use_streams_for_lob: true
        lob:
          non_contextual_creation: true
      query:
        mutation_strategy:
          global_temporary:
            drop_tables: false
            create_tables: false
          nodeValue: org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
    show-sql: true
  cache:
    type: redis
    redis:
      host: 127.0.0.1
      port: 6379
      password: admin123
      expiry-in-seconds: 43200
      socket-timeout-in-millis: 2000
      command-timeout-in-seconds: 20